# Model Architecture - ChatKasir v0

## 1. Imports Library

In [1]:
import pandas as pd

## 2. Eksplorasi Awal Dataset Food

In [21]:
# mengambil dataset food
df_food = pd.read_csv("../../data/final/food_utama_clean.csv")

# cek ukuran dataset food
print(df_food.shape)

(20568, 1)

In [24]:
# cek 10 baris awal data
df_food.head(10)

                 name
0                abon
1        abon haruwan
2           agar-agar
3  akar tonjong segar
4       aletoge segar
5       alpukat segar
6  ampas kacang hijau
7          ampas tahu
8    ampas tahu kukus
9   ampas tahu mentah

In [25]:
# cek informasi dataset
df_food.info()

<class 'pandas.DataFrame'>
RangeIndex: 20568 entries, 0 to 20567
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    20567 non-null  str
dtypes: str(1)
memory usage: 160.8 KB

In [49]:
# cek nilai kosong
df_food.isnull().sum()

name    1
dtype: int64

In [ ]:
# tampilkan baris yang kosong
df[df_food.isnull().any(axis=1)]

     name
3008  NaN

## 3. Eksplorasi Dataset Awal Slang

In [35]:
# mengambil dataset kamus slang
df_slang = pd.read_csv("../../data/final/slang_utama_clean.csv")

# cek ukuran dataset kamus
print(df_slang.shape)

(14005, 2)

In [36]:
# cek 10 baris awal data
df_slang.head(10)

     slang    formal
0   aamiin      amin
1  aamiinn      amin
2    aamin      amin
3  aammiin      amin
4     abis     habis
5   abisin  habiskan
6     acau     kacau
7    achok      ahok
8       ad       ada
9     adek      adik

In [37]:
# cek informasi dataset
df_slang.info()

<class 'pandas.DataFrame'>
RangeIndex: 14005 entries, 0 to 14004
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   slang   14005 non-null  str
 1   formal  14005 non-null  str
dtypes: str(2)
memory usage: 219.0 KB

In [46]:
# cek nilai kosong
df_slang.isnull().sum()

slang     0
formal    0
dtype: int64